# Chim Chim Cher-ee  

*Robert B. Sherman & Richard M. Sherman, 1964* ^[[*Chim Chim Cher-ee*](https://en.wikipedia.org/wiki/Chim_Chim_Cher-ee){target="_blank"} is a song from the 1964 musical motion picture *Mary Poppins*. It was originally sung by Dick Van Dyke and Julie Andrews. The song won the 1964 Academy Award for Best Original Song.]

Chim chiminey, chim chiminey, chim chim cher-ee  
A sweep is as lucky as lucky can be  
Chim chiminey, chim chiminey, chim chim cher-oo  
Good luck will rub off when I shakes 'ands with you  
Or blow me a kiss   
And that's lucky too

Now as the ladder of life as been strung  
You may think a sweep's on the bottommost rung  
Though I spends me time in the ashes and smoke  
In this 'ole wide world there's no 'appier bloke

Chim chiminey, chim chiminey, chim chim cher-ee  
A sweep is as lucky as lucky can be  
Chim chiminey, chim chiminey, chim chim cher-oo  
Good luck will rub off when I shakes 'ands with you

Chim chiminey, chim chiminey, chim chim cher-ee  
A sweep is as lucky as lucky can be  
Chim chiminey, chim chiminey, chim chim cher-oo  
Good luck will rub off when I shakes 'ands with you

I choose me bristles with pride  
Yes, I do  
A broom for the shaft and a brush for the flume

Up where the smoke is all billered and curled  
'Tween pavement and stars is the chimney sweep world  
When the's 'ardly no day  
Nor 'ardly no night  
There's things 'alf in shadow  
And 'alf way in light  
On the roof tops of London  
Cool, what a sight

Chim chiminey, chim chiminey, chim chim cher-ee  
When you're with a sweep, you're in glad company

No where is there are more 'appier crew

Than them wot sings, chim chim cher-ee, chim cher-oo  
Chim chiminey, chim chim  
Cher-ee chim cher-oo

